from __future__ import annotations

from dataclasses import dataclass

import pandas as pd


@dataclass(frozen=True)
class TemporalSplit:
    """Container for chronological train, validation, and test boundaries."""

    train_end: pd.Timestamp
    val_start: pd.Timestamp
    val_end: pd.Timestamp
    test_start: pd.Timestamp
    test_end: pd.Timestamp


def make_temporal_split(
    df: pd.DataFrame,
    config: dict,
) -> TemporalSplit:
    """Create train / validation / test splits using values defined in config.

    Validation is used for hyperparameter and model-selection decisions.
    Test remains untouched until final evaluation.

    The split is created chronologically from the final date in the dataset so
    that validation and test simulate future forecasting periods without
    leakage from later observations.
    """
    date_col = config["data"]["date_col"]
    validation_days = config["split"]["validation_days"]
    test_days = config["split"]["test_days"]

    if date_col not in df.columns:
        raise ValueError(f"Missing date column: {date_col}")

    if validation_days <= 0:
        raise ValueError("validation_days must be greater than 0")

    if test_days <= 0:
        raise ValueError("test_days must be greater than 0")

    dates = pd.to_datetime(df[date_col], errors="coerce")

    if dates.isna().any():
        raise ValueError(f"Invalid or missing values found in {date_col}")

    max_date = dates.max().normalize()
    min_date = dates.min().normalize()

    test_end = max_date
    test_start = test_end - pd.Timedelta(days=test_days - 1)

    val_end = test_start - pd.Timedelta(days=1)
    val_start = val_end - pd.Timedelta(days=validation_days - 1)

    train_end = val_start - pd.Timedelta(days=1)

    if train_end < min_date:
        raise ValueError(
            "Dataset does not contain enough history for the configured "
            "validation and test periods."
        )

    return TemporalSplit(
        train_end=train_end,
        val_start=val_start,
        val_end=val_end,
        test_start=test_start,
        test_end=test_end,
    )


def label_split(
    df: pd.DataFrame,
    split: TemporalSplit,
    config: dict,
) -> pd.Series:
    """Label every dataframe row as train, validation, test, or ignore.

    The labels are assigned using the chronological boundaries generated by
    make_temporal_split().
    """
    date_col = config["data"]["date_col"]

    if date_col not in df.columns:
        raise ValueError(f"Missing date column: {date_col}")

    dates = pd.to_datetime(df[date_col], errors="coerce")

    if dates.isna().any():
        raise ValueError(f"Invalid or missing values found in {date_col}")

    out = pd.Series(
        "ignore",
        index=df.index,
        dtype="object",
    )

    out.loc[dates <= split.train_end] = "train"
    out.loc[(dates >= split.val_start) & (dates <= split.val_end)] = "validation"
    out.loc[(dates >= split.test_start) & (dates <= split.test_end)] = "test"

    return out